# SPDX-FileCopyrightText: PyPSA Contributors
#
# SPDX-License-Identifier: MIT

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_system_dependencies:
    - git fetch --unshallow   # Needed to get version tags
    pre_create_environment:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    create_environment:
    - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
    - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --all-extras

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
