version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_system_dependencies:
    - git fetch --unshallow # Needed to get version tags
    pre_install:
    - pip install mkdocs-material
    post_install:
    - pip install git+https://github.com/PyPSA/PyPSA.git@new-opt

mkdocs:
  configuration: mkdocs.yml
  # fail_on_warning: true

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
    - dev
    - cartopy
