version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_system_dependencies:
    - git fetch --unshallow # Needed to get version tags
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
    - dev
    - cartopy
    - gurobipy
