# SPDX-FileCopyrightText: PyPSA Contributors
#
# SPDX-License-Identifier: MIT

comment: false

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
    patch:
      default:
        target: 90%
        threshold: 0%
