name: Documentation Improvement
description: Report wrong or missing documentation
labels: ["needs triage"]
type: 'Docs'

body:
- type: textarea
  id: location
  attributes:
    label: Location
    description: >
      Please provide the location of the documentation or docstring, e.g. `pypsa.Network.import_from_netcdf` or the link to the docs.
    placeholder: https://pypsa.readthedocs.io/en/latest/user-guide/contingency-analysis.html
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: Documentation problem
    description: >
      Please provide a description of what you believe needs to be fixed/ improved/ explained.
  validations:
    required: true
