#+TITLE: Python for Power System Analysis: Examples
#+OPTIONS: toc:nil        no default TOC

These examples demonstrate PyPSA using [[http://jupyter.org/][Jupyter notebooks]]. To
download the notebook files directly, replace the example file ending
=.html= with =.ipynb=.

For some of the examples you may have to download data from the
=examples= folder in the [[https://github.com/PyPSA/PyPSA][PyPSA github
repository]].

- [[./minimal_example_pf.html][*Minimal example of power flow*]] - This script performs a non-linear
  power flow for a three-node network.
- [[./minimal_example_lopf.html][*Minimal example of linear optimal power flow*]] - This script performs
  a linear optimal power flow for a three-node network.
- [[./transformer_example.html][*Transformer example*]] - Minimal example of transformer with
  non-trivial phase shift and tap ratio.
- [[https://pypsa-eur.readthedocs.io/en/latest/tutorial.html][*PyPSA-Eur tutorial*]] - Builds a month worth of data for the European
  electricity model [[https://github.com/PyPSA/pypsa-eur][PyPSA-Eur]].
- *SciGrid German network*
   - [[./scigrid-lopf-then-pf.html][*Linear OPF then non-linear PF on the SciGRID German network*]] -
     This script performs a linear optimal power flow on the [[http://scigrid.de/][SciGRID]]
     network for Germany for a full day and then examines the results.
     A full non-linear power flow is then performed on the network
     with the optimised dispatch.
  -  [[./scigrid-lopf-then-pf-plotly.html][*SciGRID example above with interactive plotting*]] - This example
     uses the interactive plotting from the [[https://plot.ly/][plotly]] library.
  - [[./scigrid-sclopf.html][*Security-constrained LOPF on the SciGRID German network*]] - This
    script performs a security-constrained linear optimal power flow
    on the [[http://scigrid.de/][SciGRID]] network for Germany, taking into account several
    possible branch outages.
  - [[./add_load_gen_trafos_to_scigrid.html][*Attaching load, generation, transformers and missing lines to the
    SciGRID German network*]] - WARNING: this script, and the referenced
    data and libraries, are no longer supported; see [[https://github.com/PyPSA/pypsa-eur][PyPSA-Eur]] for a
    newer model that covers the whole of Europe. This script attaches
    load, conventional generation data and wind and solar data,
    transformers and missing lines to the [[http://scigrid.de/][SciGRID]] network for
    Germany. It then exports the resulting network for use in the
    script above.  Only a single day's worth of data is in the [[https://github.com/PyPSA/PyPSA][PyPSA
    github repository]]; a full year (2011) of load and wind/solar data
    can be downloaded [[./scigrid-with-load-gen-trafos-2011.zip][here]].
- [[./ac-dc-lopf.html][*Meshed AC-DC network*]] - This example demonstrates multiply-connected
  AC-DC meshed networks with an example of 3 separate synchronous AC
  areas connected by a 3-node DC network.
- [[./unit-commitment.html][*Generator Unit Commitment Examples*]] - This tutorial runs through
  examples of unit commitment for generators at a single bus. Examples
  of minimum part-load, minimum up time, minimum down time, start up
  costs, shut down costs and ramp rate restrictions are shown.
- [[./simple-electricity-market-examples.html][*Simple Electricity Market Examples*]] - This tutorial gradually builds
  up more and more complicated energy-only electricity markets in
  PyPSA, starting from a single bidding zone, going up to multiple
  bidding zones connected with transmission (NTCs) along with variable
  renewables and storage.
-  [[./generation-investment-screening-curve.html][*Generation Investment Screening Curve*]] - This examples looks at
   the long-term equilibrium of generation investment for a given load
   profile and compares it to a screening curve analysis.
- *Coupling to Other Energy Sectors*
  - [[./lopf-with-heating.html][*Linear optimal power flow with coupling to the heating sector*]] - In
    this example three locations are optimised, each with an electric
    bus and a heating bus and corresponding loads. At each location
    the electric and heating buses are connected with heat pumps; heat
    can also be supplied to the heat bus with a boiler. The electric
    buses are connected with transmission lines and there are
    electrical generators at two of the nodes.
  - [[./power-to-gas-boiler-chp.html][*Power-to-Gas with Gas Boiler and Combined-Heat-and-Power unit*]]
  - [[./chp-fixed-heat-power-ratio.html][*Demonstration of Link with multiple outputs: Combined-Heat-and-Power (CHP) with fixed heat-power ratio*]]
  - [[./power-to-heat-water-tank.html][*Power-to-Heat with Water Tank*]]
  - [[./battery-electric-vehicle-charging.html][*Transport: Charging Battery Electric Vehicle with Solar Panel*]]
  - [[./chained-hydro-reservoirs.html][*Chained Hydroelectric Reservoirs*]]
  - [[./biomass-synthetic-fuels-carbon-management.html][*Biomass, synthetic fuels and carbon management*]]
  - [[./replace-generator-storage-units-with-store.html][*Replacing Generators and Storage Units with Fundamental Stores and
    Links*]] - This notebook demonstrates how generators and storage
    units can be replaced by more fundamental components (Stores and
    Links), and how their parameters map to each other.
- [[./logging-demo.html][*Logging*]] - How to control the level of logging that PyPSA reports
  back, e.g. error/warning/info/debug messages.
- [[https://github.com/PyPSA/pypsa-eur][*PyPSA-Eur*]]: An Open Optimisation Model of the European Transmission System
- [[https://github.com/PyPSA/pypsa-za][*PyPSA-ZA*]]: PyPSA Model of the South African Energy System
- [[https://zenodo.org/record/1146665][*Sector-Coupled European Dataset*]] - Full dataset and code from [[https://arxiv.org/abs/1801.05290][Synergies of sector coupling and transmission extension in a cost-optimised, highly renewable European energy system]], Energy, Volume 160, Pages 720-739, 2018, [[https://arxiv.org/abs/1801.05290][postprint arXiv:1801.05290]], DOI: [[https://doi.org/10.1016/j.energy.2018.06.222][10.1016/j.energy.2018.06.222]].
- [[https://zenodo.org/record/804337][*European One-Node-Per-Country Dataset*]] - Full dataset and code from [[https://doi.org/10.1016/j.energy.2017.06.004][The Benefits of Cooperation in a Highly Renewable European Electricity Network]], Energy, Volume 134, 1 September 2017, Pages 469-481, [[https://arxiv.org/abs/1704.05492][preprint]].
- [[https://github.com/PyPSA/WHOBS][*WHOBS*]]: Optimal Wind+Hydrogen+Other+Battery+Solar (WHOBS) electricity systems for European countries
- [[https://github.com/openego][*open-Ego project*]] - The project open-eGo aims to develop a transparent, inter-grid-level operating grid planning tool to investigate economic viable grid expansion scenarios considering alternative flexibility options such as storages or redispatch. It uses PyPSA.




If you have a nice example of using PyPSA, send your Jupyter notebook to
Tom Brown (firstname.lastname@kit.edu).
