name: Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
