# SPDX-FileCopyrightText: PyPSA Contributors
#
# SPDX-License-Identifier: MIT

name: SMS++ Tests


on:
  push:
    branches:
    - master
    - release-branch-v*
  pull_request:
    branches: ["*"]
  schedule:
  - cron: "0 5 * * *"
  workflow_dispatch:

# Cancel any in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_with_conda_smspp:
    # Test package with SMS++ installed from conda-forge
    name: Test package with SMSpp from conda-forge (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.13"
    defaults:
      run:
        shell: bash -el {0}
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0 # Needed for setuptools_scm

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: test-env
        python-version: ${{ matrix.python-version }}

    - name: Install SMS++ from conda-forge
      run: |
        conda install -y -c conda-forge smspp-project

    - name: Install package and dependencies
      run: |
        pip install '.[dev,smspp]'

    - name: List environment
      run: |
        conda list

    - name: Test package with SMSpp
      run: |
        pytest test/test_smspp.py
